# Data Merge

In [2]:
import pandas as pd

# example datasets for data merging
data = {
    'id': [1, 2, 3],
    'name': ['Ahmed', 'Fatima', 'Ali'],
    'age': [25, 22, 30]
}
df1 = pd.DataFrame(data)
df1.head()

   id    name  age
0   1   Ahmed   25
1   2  Fatima   22
2   3     Ali   30

In [3]:
# Dataset 2: Additional Information
data2 = {
    'id': [1, 2, 3],
    'city': ['Karachi', 'Lahore', 'Islamabad'],
    'occupation': ['Engineer', 'Doctor', 'Teacher']
}
df2 = pd.DataFrame(data2)
df2.head()

   id       city occupation
0   1    Karachi   Engineer
1   2     Lahore     Doctor
2   3  Islamabad    Teacher

In [4]:
# merging data frams on the basis of id
merged_df = pd.merge(df1, df2, on='id')
merged_df.head()

   id    name  age       city occupation
0   1   Ahmed   25    Karachi   Engineer
1   2  Fatima   22     Lahore     Doctor
2   3     Ali   30  Islamabad    Teacher

________
# Concatenation

In [8]:
import pandas as pd

# example datasets
# dataset 1
data1 = {'Name': ['Ahmed', 'Ali', 'Fatima'], 'Age': [28, 34, 29]}
# Dataset 2 - More Pakistani Names and Ages
data2 = {'Name': ['Sara', 'Usman', 'Aisha'], 'Age': [29, 35, 27]}
# Dataset 3 - Cities and Provinces in Pakistan
data3 = {'City': ['Karachi', 'Lahore', 'Islamabad'], 'Province': ['Sindh', 'Punjab', 'Islamabad']}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
df3 = pd.DataFrame(data3)

# concatenating rows
concatenated_rows = pd.concat([df1, df2])

# concatenating columns
# Note: For a meaningful column-wise concatenation, dataframes should have the same number of rows.
concatenated_columns = pd.concat([df1, df3], axis=1)
print(concatenated_rows)
print("-----------------------------")
print(concatenated_columns)

     Name  Age
0   Ahmed   28
1     Ali   34
2  Fatima   29
0    Sara   29
1   Usman   35
2   Aisha   27
-----------------------------
     Name  Age       City   Province
0   Ahmed   28    Karachi      Sindh
1     Ali   34     Lahore     Punjab
2  Fatima   29  Islamabad  Islamabad